sudo: true
dist: trusty
#group: deprecated-2017Q3
language: python
python:
  - "3.6"
# install pg_chameleon
install: "pip install ."

services:
  - mysql

addons:
  postgresql: "10"
  
before_script:
 - tests/setup_db.sh
 
 # command to run tests
script: tests/test.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/166d0e880973f957205f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

