---
#global settings
pid_dir: '~/.pg_chameleon/pid/'
log_dir: '~/.pg_chameleon/logs/'
log_dest: stdout
log_level: debug
log_days_keep: 10


#postgres  destination connection
pg_conn:
    host: "localhost"
    port: "5432"    
    user: "usr_replica"
    password: "never_commit_passwords"
    database: "db_replica"
    charset: "utf8"
    

sources:
    example:
        db_conn:
                host: "localhost"
                port: "3306"
                user: "usr_replica"
                password: "never_commit_passwords"
                database:  "db_replica"
                charset: 'utf8'
        schema_mappings:
                my_schema: dest_schema
        limit_tables:
        skip_tables:
        copy_max_memory: "300M"
        grant_select_to:
            - usr_readonly
        create_views_in_schema:
            - sch_readonly
        lock_timeout: "120s"
        my_server_id: 100
        replica_batch_size: 1000
        batch_retention: '1 day'
        copy_max_memory: 300M
        copy_mode: 'file'  
        out_dir: /tmp


# type_override allows the user to override the default type conversion into a different one. 
# override_to specifies the destination type which must be a postgresql type and the type cast should be possible
# override_tables specifies which tables the override apply. If set to "*" then applies to all tables in the replicated schema
# the override applies during the init_replica,sync_tables process and for each matching DDL (create table/alter table)
type_override:
    "tinyint(1)":
        override_to: boolean
        override_tables:
            - "*"
